export const copy = {
  sheetTitle: "Account & Settings",
  signInPrompt: "Sign in to WetinDey",
  signInSubtitle: "Save places, track prices, and contribute local observations.",
  emailLabel: "Email address",
  emailPlaceholder: "name@example.com",
  sendCodeButton: "Send OTP Code",
  resendCodeButton: "Resend Code",
  enterCodeLabel: "Enter 6-digit code",
  verifyCodeButton: "Verify & Sign In",
  signOutButton: "Sign Out",
  manageProfileLabel: "Manage Profile",
  myReportsLabel: "My Reports",
  reportProblemLabel: "Report a Problem",
  aboutLabel: "About WetinDey",
  changeAreaLabel: "Location Area",
  settingsLabel: "Settings",
};
