import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { moderatorControlForContract } from "./contribution-moderator-control";
assert.deepEqual(moderatorControlForContract.parseArguments(["--target-database", "preview", "--apply"]), { "target-database": "preview", apply: true });
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_database/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.inet_server_addr/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_setting\('neon\.endpoint_id', true\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_setting\('neon\.project_id', true\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_setting\('neon\.branch_id', true\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.pg_settings/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /identity_settings_locked/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /setting\.context IN \('superuser', 'postmaster'\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /NOT role\.rolsuper/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /current_user = session_user AS direct_login/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /'wetindey_contribution_owner', 'SET'/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /incompatible_memberships_absent/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /WITH RECURSIVE membership_path/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.pg_auth_members/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /bool_and\(NOT membership_path\.set_option\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /membership_closure_safe/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /ARRAY\[\$2::name\]/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.to_regprocedure/);
assert.doesNotMatch(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.(?:current_user|session_user)/, "PostgreSQL identity keywords are not schema-qualified expressions");
assert.deepEqual(moderatorControlForContract.CONTROL_SIGNATURES, ["public.contribution_set_moderator_assignment(uuid,uuid,public.contribution_assignment_status,timestamp with time zone,timestamp with time zone,uuid,uuid)", "public.contribution_set_control(uuid,uuid,boolean,boolean,integer,integer,integer,integer,integer,integer,text)"]);
const target = { host: "ep-preview-proof-ab12cd34.c-10.us-east-1.aws.neon.tech", project: "wetindey", branch: "preview", database: "neondb" };
const actors = { moderator: "10000000-0000-4000-8000-000000000001", issuer: "10000000-0000-4000-8000-000000000002", reviewer: "10000000-0000-4000-8000-000000000003", actor: "10000000-0000-4000-8000-000000000002" };
const environment = { CONTRIBUTION_CONTROL_EXPECTED_HOST: target.host, CONTRIBUTION_CONTROL_EXPECTED_PROJECT: target.project, CONTRIBUTION_CONTROL_EXPECTED_BRANCH: target.branch, CONTRIBUTION_CONTROL_EXPECTED_DATABASE: target.database, CONTRIBUTION_CONTROL_ALLOWED_TARGETS: `wetindey/preview/${target.host}/neondb`, CONTRIBUTION_CONTROL_MODERATOR_ACCOUNT_ID: actors.moderator, CONTRIBUTION_CONTROL_ISSUER_ACCOUNT_ID: actors.issuer, CONTRIBUTION_CONTROL_REVIEWER_ACCOUNT_ID: actors.reviewer, CONTRIBUTION_CONTROL_ACTOR_ACCOUNT_ID: actors.actor };
assert.deepEqual(moderatorControlForContract.targetFromEnvironment(environment), target);
assert.equal(moderatorControlForContract.targetIsAllowed(environment, target), true);
assert.equal(moderatorControlForContract.targetIsAllowed(environment, { ...target, database: "other" }), false);
assert.equal(moderatorControlForContract.sameTarget(target, { ...target, branch: "production" }), false);
assert.deepEqual(moderatorControlForContract.verifiedActorsFromEnvironment(environment), actors);
assert.equal(moderatorControlForContract.commandActorsMatch("assign", { "account-id": actors.moderator, "issued-by": actors.issuer, "reviewed-by": actors.reviewer }, actors), true);
assert.equal(moderatorControlForContract.commandActorsMatch("assign", { "account-id": actors.moderator, "issued-by": actors.issuer, "reviewed-by": actors.issuer }, actors), false);
assert.equal(moderatorControlForContract.commandActorsMatch("control", { "actor-id": actors.actor }, actors), true);
const approvedActors = Object.fromEntries(Object.entries(actors).map(([role, id]) => [role, moderatorControlForContract.actorDigest(id)])) as Record<keyof typeof actors, string>;
assert.equal(moderatorControlForContract.actorsAreApproved(target, actors, { [`${target.project}/${target.branch}/${target.host}/${target.database}`]: approvedActors }), true);
assert.equal(moderatorControlForContract.actorsAreApproved(target, { ...actors, moderator: "10000000-0000-4000-8000-000000000004" }, { [`${target.project}/${target.branch}/${target.host}/${target.database}`]: approvedActors }), false);
assert.equal(moderatorControlForContract.actorsAreApproved({ ...target, branch: "production" }, actors, { [`${target.project}/${target.branch}/${target.host}/${target.database}`]: approvedActors }), false);
assert.equal(moderatorControlForContract.verifiedActorsFromEnvironment({ ...environment, CONTRIBUTION_CONTROL_REVIEWER_ACCOUNT_ID: actors.issuer }), null, "governance identities must be distinct");
assert.equal(moderatorControlForContract.verifiedActorsFromEnvironment({ ...environment, CONTRIBUTION_CONTROL_MODERATOR_ACCOUNT_ID: "not-a-uuid" }), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost(target.host), "ep-preview-proof-ab12cd34");
assert.equal(moderatorControlForContract.neonEndpointFromHost("169.254.254.254"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof."), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof.attacker"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof.us-east-1.aws.neon.tech.attacker"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost(" EP-preview-proof.us-east-1.aws.neon.tech"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-foo--bar.us-east-1.aws.neon.tech"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof-ab12cd34.c-0.us-east-1.aws.neon.tech"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof-ab12cd34.c-01.us-east-1.aws.neon.tech"), null);
assert.equal(moderatorControlForContract.neonEndpointFromHost("ep-preview-proof-ab12cd34.c-999999.us-east-1.aws.neon.tech"), null);
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, neon_endpoint_id: "ep-preview-proof-ab12cd34", neon_project_id: target.project, neon_branch_id: target.branch }), true);
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, neon_endpoint_id: null, neon_project_id: target.project, neon_branch_id: target.branch }), false, "missing Neon endpoint identity must fail closed");
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, neon_endpoint_id: "ep-production", neon_project_id: target.project, neon_branch_id: target.branch }), false, "mismatched Neon endpoint must fail closed");
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, neon_endpoint_id: "ep-preview-proof-ab12cd34", neon_project_id: target.project, neon_branch_id: null }), false, "missing Neon identity must fail closed");
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, neon_endpoint_id: "ep-preview-proof-ab12cd34", neon_project_id: target.project, neon_branch_id: "production" }), false, "mismatched Neon identity must fail closed");
const source = readFileSync("scripts/contributions/contribution-moderator-control.ts", "utf8");
assert.match(source, /BEGIN ISOLATION LEVEL SERIALIZABLE/);
assert.equal(source.match(/await assertCapability\(\);/g)?.length, 2, "capability is checked before mutation and before commit");
assert.match(source, /await client\.query\("ROLLBACK"\)/);
console.log("Contribution moderator control contracts satisfied.");
