import assert from "node:assert/strict";
import { moderatorControlForContract } from "./contribution-moderator-control";
assert.deepEqual(moderatorControlForContract.parseArguments(["--target-database", "preview", "--apply"]), { "target-database": "preview", apply: true });
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_database/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.inet_server_addr/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_setting\('neon\.project_id', true\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.current_setting\('neon\.branch_id', true\)/);
assert.match(moderatorControlForContract.CAPABILITY_SQL, /pg_catalog\.to_regprocedure/);
assert.deepEqual(moderatorControlForContract.CONTROL_SIGNATURES, ["public.contribution_set_moderator_assignment(uuid,uuid,public.contribution_assignment_status,timestamp with time zone,timestamp with time zone,uuid,uuid)", "public.contribution_set_control(uuid,uuid,boolean,boolean,integer,integer,integer,integer,integer,integer,text)"]);
const target = { host: "203.0.113.9", project: "wetindey", branch: "preview", database: "neondb" };
const environment = { CONTRIBUTION_CONTROL_EXPECTED_HOST: target.host, CONTRIBUTION_CONTROL_EXPECTED_PROJECT: target.project, CONTRIBUTION_CONTROL_EXPECTED_BRANCH: target.branch, CONTRIBUTION_CONTROL_EXPECTED_DATABASE: target.database, CONTRIBUTION_CONTROL_ALLOWED_TARGETS: "wetindey/preview/203.0.113.9/neondb" };
assert.deepEqual(moderatorControlForContract.targetFromEnvironment(environment), target);
assert.equal(moderatorControlForContract.targetIsAllowed(environment, target), true);
assert.equal(moderatorControlForContract.targetIsAllowed(environment, { ...target, database: "other" }), false);
assert.equal(moderatorControlForContract.sameTarget(target, { ...target, branch: "production" }), false);
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, server_host: target.host, neon_project_id: target.project, neon_branch_id: target.branch }), true);
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, server_host: target.host, neon_project_id: target.project, neon_branch_id: null }), false, "missing Neon identity must fail closed");
assert.equal(moderatorControlForContract.targetMatchesProbe(target, { database_name: target.database, server_host: target.host, neon_project_id: target.project, neon_branch_id: "production" }), false, "mismatched Neon identity must fail closed");
console.log("Contribution moderator control contracts satisfied.");
